### ISSUE TITLE
New base.html file needed

### ISSUE THREAD

**Issue by MakeMeSenpai** [MakeMeSenpai/dont_mix_that#1]
This will be the parent of most, if not all our html pages. We will be using templating and flask. I make this issue because this is the way to organize projects in git. So if there are any bugs or issues you find in this code, be sure to mark them with the correct label and place them here. Then you can assign who's responsibility it is to take care of it. From there, milestones will be created, with the project itself.

**Comment by reikamoon** [comment]
Basic Base.html has been created and added to the templates folder.

**Comment by reikamoon** [comment]
home.html and foundations for flask has been added.
