### ISSUE TITLE
Wiki, Read Me, and Community

### ISSUE THREAD

**Issue by MakeMeSenpai** [MakeMeSenpai/dont_mix_that#2]
This is just to improve clarity about our project aspects, and make a proper looking GitHub project. Read Me should include: information about how to run your code, a brief description on what your project is, and should contain all resources and references. Wiki should be a blueprint of our project, and help users navigate threw our code easier. Be sure to comment code so that it can be easily read and easily understood (write them as if you are teacher your past self, so that when your future self forgets, they can still understand it). And lastly meeting all of GitHub's community pages, in order to provide the proper amount of information for others who will see our project.

**Comment by The1stAnthony** [comment]
Community is complete. Read Me and Wiki still needs work.
